basePath: /user-service
definitions:
  handler.BatchRequest:
    properties:
      ids:
        items:
          type: string
        type: array
    type: object
  req.UserChangePasswordReq:
    properties:
      new_password:
        type: string
      old_password:
        type: string
    required:
    - new_password
    - old_password
    type: object
  req.UserLoginReq:
    properties:
      password:
        type: string
      phone:
        type: string
    required:
    - password
    - phone
    type: object
  req.UserRegReq:
    properties:
      address:
        type: string
      avatar:
        type: string
      birthday:
        type: string
      email:
        type: string
      full_name:
        type: string
      gender:
        enum:
        - male
        - female
        type: string
      phone:
        type: string
      role:
        enum:
        - patient
        - doctor
        - admin
        type: string
    required:
    - address
    - birthday
    - email
    - full_name
    - gender
    - phone
    - role
    type: object
  req.UserUpdateReq:
    properties:
      address:
        type: string
      avatar:
        type: string
      birthday:
        type: string
      email:
        type: string
      full_name:
        type: string
      gender:
        type: string
    required:
    - address
    - avatar
    - birthday
    - email
    - full_name
    - gender
    type: object
  res.LoginRes:
    properties:
      access_token:
        type: string
      address:
        type: string
      avatar:
        type: string
      birthday:
        type: string
      created_at:
        type: string
      email:
        type: string
      full_name:
        type: string
      gender:
        type: string
      id:
        type: string
      password:
        type: string
      phone:
        type: string
      role:
        type: string
      updated_at:
        type: string
    type: object
  response.ResErr:
    properties:
      errors:
        items:
          type: string
        type: array
      message:
        type: string
      status:
        type: string
    type: object
  response.ResOk:
    properties:
      data: {}
      message:
        type: string
      status:
        type: string
    type: object
host: localhost:3080
info:
  contact: {}
  description: API documentation for Hospital Microservice
  title: Hospital Microservice API
  version: "1.0"
paths:
  /account/batch:
    post:
      consumes:
      - application/json
      description: Return list of users for given ids (batch)
      parameters:
      - description: IDs
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handler.BatchRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items: {}
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ResErr'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ResErr'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ResErr'
      summary: Get multiple user details by ids
      tags:
      - account
  /account/delete/{id}:
    delete:
      description: Soft delete a user by ID (flag as deleted, not permanent)
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ResErr'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ResErr'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/response.ResErr'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ResErr'
      security:
      - BearerAuth: []
      summary: Delete user (admin only)
      tags:
      - account
  /account/detail/{id}:
    get:
      consumes:
      - application/json
      description: Retrieve detailed information for a specific user
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ResErr'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ResErr'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/response.ResErr'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ResErr'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ResErr'
      security:
      - BearerAuth: []
      summary: Get user detail
      tags:
      - account
  /account/doctors:
    get:
      consumes:
      - application/json
      description: Patients can see available doctors to make appointments
      parameters:
      - description: Limit
        in: query
        name: limit
        type: integer
      - description: Page
        in: query
        name: page
        type: integer
      - description: Sort
        in: query
        name: sort
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ResErr'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ResErr'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/response.ResErr'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ResErr'
      security:
      - BearerAuth: []
      summary: Get doctors with pagination
      tags:
      - account
  /account/edit/{id}:
    patch:
      consumes:
      - application/json
      description: Update user data by admin
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      - description: Update Request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/req.UserUpdateReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ResErr'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ResErr'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/response.ResErr'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ResErr'
      security:
      - BearerAuth: []
      summary: Edit any user (Admin only)
      tags:
      - account
  /account/filter:
    get:
      consumes:
      - application/json
      description: Filter users with pagination (only admin can access)
      parameters:
      - description: Limit
        in: query
        name: limit
        type: integer
      - description: Page
        in: query
        name: page
        type: integer
      - description: Sort
        in: query
        name: sort
        type: string
      - description: Role filter (admin|doctor|patient)
        in: query
        name: role
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ResErr'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ResErr'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/response.ResErr'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ResErr'
      security:
      - BearerAuth: []
      summary: Filter users with pagination
      tags:
      - account
  /account/patients:
    get:
      consumes:
      - application/json
      description: Doctors can see patients to make appointments
      parameters:
      - description: Limit
        in: query
        name: limit
        type: integer
      - description: Page
        in: query
        name: page
        type: integer
      - description: Sort
        in: query
        name: sort
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ResErr'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ResErr'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/response.ResErr'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ResErr'
      security:
      - BearerAuth: []
      summary: Get patients with pagination
      tags:
      - account
  /account/profile:
    get:
      consumes:
      - application/json
      description: Retrieve profile for the authenticated user (from JWT claims)
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ResErr'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ResErr'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ResErr'
      security:
      - BearerAuth: []
      summary: Get current user profile
      tags:
      - account
  /account/update:
    patch:
      consumes:
      - application/json
      description: Update profile data for the authenticated user
      parameters:
      - description: Update Request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/req.UserUpdateReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ResErr'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ResErr'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ResErr'
      security:
      - BearerAuth: []
      summary: Update current user
      tags:
      - account
  /auth/change-password:
    patch:
      consumes:
      - application/json
      description: Update password for the authenticated user
      parameters:
      - description: Change Password Request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/req.UserChangePasswordReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ResErr'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ResErr'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ResErr'
      security:
      - BearerAuth: []
      summary: Change password
      tags:
      - auth
  /auth/login:
    post:
      consumes:
      - application/json
      description: Authenticate user and return JWT token
      parameters:
      - description: Login Request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/req.UserLoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.LoginRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ResErr'
      summary: Login user
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Create a new user account
      parameters:
      - description: Register Request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/req.UserRegReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResOk'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ResErr'
      summary: Register a new user
      tags:
      - auth
securityDefinitions:
  BearerAuth:
    description: Type "Bearer {your-token}"
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
