// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/prescription-service/prescriptions": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new prescription",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "prescription"
                ],
                "summary": "Create prescription",
                "parameters": [
                    {
                        "description": "Prescription Create Request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/req.PrescriptionCreateReq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response.ResOk"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.ResErr"
                        }
                    }
                }
            }
        },
        "/prescription-service/prescriptions/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve details of a prescription by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "prescription"
                ],
                "summary": "Get prescription details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Prescription ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/res.PrescriptionDetailRes"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ResErr"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "req.PrescriptionCreateReq": {
            "type": "object",
            "required": [
                "appointment_id",
                "doctor_id",
                "dosage",
                "drug_name",
                "patient_id"
            ],
            "properties": {
                "appointment_id": {
                    "type": "string"
                },
                "doctor_id": {
                    "type": "string"
                },
                "dosage": {
                    "type": "string"
                },
                "drug_name": {
                    "type": "string"
                },
                "instruction": {
                    "type": "string"
                },
                "patient_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "not_collected",
                        "collected"
                    ]
                }
            }
        },
        "res.PrescriptionDetailRes": {
            "type": "object",
            "properties": {
                "appointment_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "doctor_id": {
                    "type": "string"
                },
                "dosage": {
                    "type": "string"
                },
                "drug_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "instruction": {
                    "type": "string"
                },
                "patient_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "response.ResErr": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "response.ResOk": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer {your-token}\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3080",
	BasePath:         "/prescription-service",
	Schemes:          []string{},
	Title:            "Hospital Microservice API",
	Description:      "API documentation for Hospital Microservice",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
