user:
	TEMP="C:/Users/Nguyen Hi Huu/AppData/Local/Temp" \
	TMP="C:/Users/Nguyen Hi Huu/AppData/Local/Temp" \
	GOPATH="C:/Users/Nguyen Hi Huu/go" \
	GOMODCACHE="C:/Users/Nguyen Hi Huu/go/pkg/mod" \
	go run user-service/cmd/app/main.go
